### PR TITLE
Code style fixes

### PR DESCRIPTION
**Pull request by FrittenKeeZ**
@ryanmitchell this also fixes a typo in facade import of `TermQueryBuilder.php`

### CODE REVIEW

**Comment by ryanmitchell** [comment]
Someone else raised a similar PR and I think its better opened against the main repo once this merges rather than trying to include it. It keeps the PRs focused on one thing.

**Comment by FrittenKeeZ** [comment]
> Someone else raised a similar PR and I think its better opened against the main repo once this merges rather than trying to include it. It keeps the PRs focused on one thing.

This isn't only code cleanup.

**Comment by ryanmitchell** [comment]
Then split out what isnt clean up into a different PR

**Comment by FrittenKeeZ** [comment]
@ryanmitchell do what you want - stubs doesn't follow Laravel style and `AssetRepository` is indented extra

**Pull request closed without merging**
