### PR TITLE
Migration optimizations

### PR DESCRIPTION
**Pull request by FrittenKeeZ**
Added indexes to all tables where beneficial.
I need to test import commands with a big site to see if anything else is needed.

### CODE REVIEW

**Comment by ryanmitchell** [comment]
Just checking if you are planning on updating this and resolving the merge conflicts?

**Comment by FrittenKeeZ** [comment]
I am, it's on my list for today :)

**Comment by FrittenKeeZ** [comment]
@ryanmitchell I'm testing the last import tomorrow - hopefully I'll have time to make an import for assets metadata as well

**Comment by FrittenKeeZ** [comment]
@ryanmitchell I'll look at revisions import in another PR

**Comment by ryanmitchell** [comment]
Thank you!

**Pull request merged**
