### PR TITLE
Bring back file submissions for Form migrations

### PR DESCRIPTION
**Pull request by okaufmann**
Hi

To migrate Forms fileSubmissions needs to be places into the new Model. Otherwise the following error will occur:

```
Too few arguments to function Statamic\Data\AbstractAugmented::get(), 0 passed in /Users/okaufmann/Code/novu/hepverlag-cms/vendor/statamic/cms/src/Data/AbstractAugmented.php on line 52 and exactly 1 expected
```

### CODE REVIEW

**Comment by ryanmitchell** [comment]
If this is migration specific I wonder if there is another approach that would avoid this being present in the eloquent class?

**Comment by okaufmann** [comment]
@ryanmitchell It is. I moved it into a separate namespace, maybe we need more helper code which should not be placed in the certain models.

**Comment by ryanmitchell** [comment]
Thanks for this - I'm going to do another pass at the imports again next week. I cant help feeling theres a better way I've missed so will have another go at them.

**Comment by ryanmitchell** [comment]
Thanks again, but I'm going to close this in favour of the commit here:
https://github.com/ryanmitchell/eloquent-driver/commit/b7ae4236e242e9f6800cd876a0671dbed956ac30

**Comment by okaufmann** [comment]
Nice! No problemo

**Pull request closed without merging**
